lint

diff --git a/bin/server-config/configure b/bin/server-config/configure
--- a/bin/server-config/configure
+++ b/bin/server-config/configure
@@ -15,7 +15,7 @@ function finish {
   rm -f "$tmp" "$tmp2"
 
   if [ "$rv" -ne "0" ]; then
-    echo -e "\e[91mThere were errors."
+    echo -e "\\e[91mThere were errors."
   fi
 }
 trap finish EXIT
@@ -131,8 +131,8 @@ ensure_varnish() {
 }
 
 fn_update() {
-  exec > >(while read -r ln; do printf "\e[90m%-16s>\e[39m %s\\n" "$(cat "$tmp2")" "$ln"; done)
-  exec 2> >(while read -r ln; do printf "\e[91m%-16s>\e[39m %s\\n" "$(cat "$tmp2")" "$ln" >&2; done)
+  exec > >(while read -r ln; do printf "\\e[90m%-16s>\\e[39m %s\\n" "$(cat "$tmp2")" "$ln"; done)
+  exec 2> >(while read -r ln; do printf "\\e[91m%-16s>\\e[39m %s\\n" "$(cat "$tmp2")" "$ln" >&2; done)
 
   if ifconfig | grep --silent addr:192.168; then
     err "doesn't look like we're on a droplet, giving up"
